import type { Metadata } from "next";
import "./globals.css";
import { font_monospace, font_sans } from "@/functions/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-BR'>
			<body className={font_monospace.variable}>{children}</body>
		</html>
	);
}
